version: "3.9"
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
    express:
        build: "./server"
        ports:
            - "8000:8000"
        volumes:
            - type: bind
              source: ./server/src
              target: /app/src
            - type: bind
              source: ./server/node_modules/@prisma
              target: /app/node_modules/@prisma
            - type: bind
              source: ./server/node_modules/.prisma
              target: /app/node_modules/.prisma
    frontend:
        build: "./front-end"
        ports:
            - "3000:3000"
        volumes:
            - type: bind
              source: ./front-end/src
              target: /app/src
