version: "3.9"
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready']
            interval: 10s
            timeout: 5s
            retries: 5
    express:
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
        build: "./server"
        ports:
            - "8000:8000"
        volumes:
            - type: bind
              source: ./server/src
              target: /app/src
        depends_on:
            postgres:
                condition: service_healthy
    frontend:
        build: "./front-end"
        ports:
            - "3000:3000"
        volumes:
            - type: bind
              source: ./front-end/src
              target: /app/src
